### ISSUE TITLE
[suggestion] Leave the bot in the discord channel for an extended period of time

### ISSUE THREAD

**Issue by Whitelisted1** [porridgewithraisins/jam-bot#10]
Maybe add a feature so that when a user leaves, the bot pauses the song and stays in the discord channel for an extended period of time, and when a user rejoins, it starts playing the initial song

**Comment by porridgewithraisins** [comment]
Hi, I'm releasing the next version after testing some other stuff (code is currently in dev branch if you wanna look at it). In that, `aloneTimeout` is a configuration (default 15 seconds) that you can give which will dictate how long the bot will remain alone in a voice channel.
Thanks for the suggestion!
